### ISSUE TITLE
ImproperlyConfigured: Error importing module django_hosts.middleware: "No module named lru_cache"

### ISSUE THREAD

**Issue by umrashrf** [jezdez/django-hosts#34]
I get this exception with 1.2 version. I'm using it with Django 1.6.10.

```
[14/May/2015 18:52:35] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/me/dev/venvs/proj/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/home/me/dev/venvs/proj/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/me/dev/venvs/proj/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
    mw_class = import_by_path(middleware_path)
  File "/home/me/dev/venvs/proj/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_by_path
    sys.exc_info()[2])
  File "/home/me/dev/venvs/proj/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 21, in import_by_path
    module = import_module(module_path)
  File "/home/me/dev/venvs/proj/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/me/dev/venvs/proj/local/lib/python2.7/site-packages/django_hosts/middleware.py", line 5, in <module>
    from .resolvers import get_host_patterns, get_host
  File "/home/me/dev/venvs/proj/local/lib/python2.7/site-packages/django_hosts/resolvers.py", line 15, in <module>
    from django.utils.lru_cache import lru_cache
ImproperlyConfigured: Error importing module django_hosts.middleware: "No module named lru_cache"
```

**Comment by jezdez** [comment]
Support for Django 1.6 was removed in 1.2 as it's not secure anymore. Please either upgrade to a newer version of Django (I know it takes time) or stick to django-hosts 1.1 till you have.

**Comment by andreipak** [comment]
We use django-crispy-forms 1.6.0 with Django 1.6.7
